"""
state.py - Shared State Definition for Phase 2 LangGraph Workflow
All agents read from and write to this shared state.
"""

from typing import TypedDict, List, Optional, Annotated
import operator


class DialogueLine(TypedDict):
    speaker: str
    line: str
    visual_cue: str


class SceneTask(TypedDict):
    scene_id: int
    location: str
    characters: List[str]
    dialogue: List[DialogueLine]


class GraphState(TypedDict):
    """
    Shared state across all agents in the LangGraph workflow.
    Annotated[List, operator.add] means each agent APPENDS to these lists
    when running in parallel — LangGraph merges them automatically.
    """
    scenes: List[SceneTask]                              # Input scenes from scene_manifest.json
    task_graph: Optional[dict]                           # Generated by Scene Parser Agent
    completed_audio: Annotated[List[str], operator.add]  # WAV paths from Voice Synth Agent
    completed_video: Annotated[List[str], operator.add]  # Frame dirs from Video+Face Swap Agents
    final_outputs: Annotated[List[str], operator.add]    # Final MP4 paths from Lip Sync Agent
    errors: Annotated[List[str], operator.add]           # Error log from any agent
